# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefoonNr', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=255)),
                ('bericht', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Klassen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('numeriekeCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leraren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('voornaam', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Richtingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('omschrijving', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='klassen',
            name='leeraar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Leraren'),
        ),
        migrations.AddField(
            model_name='klassen',
            name='richting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Richtingen'),
        ),
    ]
